-- Atlas Training cloud tables
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.weights (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  weigh_date date not null,
  weight_kg numeric(5,2) not null check (weight_kg > 0),
  created_at timestamptz not null default now(),
  unique (user_id, weigh_date)
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_date date not null,
  workout_day text not null,
  rating integer check (rating between 1 and 5),
  duration_minutes integer check (duration_minutes >= 0),
  notes text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  completion_key text not null,
  is_complete boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (user_id, completion_key)
);

alter table public.weights enable row level security;
alter table public.sessions enable row level security;
alter table public.completions enable row level security;

grant select, insert, update, delete on public.weights to authenticated;
grant select, insert, update, delete on public.sessions to authenticated;
grant select, insert, update, delete on public.completions to authenticated;

create policy "weights_select_own" on public.weights
for select to authenticated using (auth.uid() is not null and auth.uid() = user_id);
create policy "weights_insert_own" on public.weights
for insert to authenticated with check (auth.uid() is not null and auth.uid() = user_id);
create policy "weights_update_own" on public.weights
for update to authenticated using (auth.uid() is not null and auth.uid() = user_id)
with check (auth.uid() is not null and auth.uid() = user_id);
create policy "weights_delete_own" on public.weights
for delete to authenticated using (auth.uid() is not null and auth.uid() = user_id);

create policy "sessions_select_own" on public.sessions
for select to authenticated using (auth.uid() is not null and auth.uid() = user_id);
create policy "sessions_insert_own" on public.sessions
for insert to authenticated with check (auth.uid() is not null and auth.uid() = user_id);
create policy "sessions_update_own" on public.sessions
for update to authenticated using (auth.uid() is not null and auth.uid() = user_id)
with check (auth.uid() is not null and auth.uid() = user_id);
create policy "sessions_delete_own" on public.sessions
for delete to authenticated using (auth.uid() is not null and auth.uid() = user_id);

create policy "completions_select_own" on public.completions
for select to authenticated using (auth.uid() is not null and auth.uid() = user_id);
create policy "completions_insert_own" on public.completions
for insert to authenticated with check (auth.uid() is not null and auth.uid() = user_id);
create policy "completions_update_own" on public.completions
for update to authenticated using (auth.uid() is not null and auth.uid() = user_id)
with check (auth.uid() is not null and auth.uid() = user_id);
create policy "completions_delete_own" on public.completions
for delete to authenticated using (auth.uid() is not null and auth.uid() = user_id);
